### ISSUE TITLE
dekstops

### ISSUE THREAD

**Issue by gedw99** [johbar/text-extraction-service#6]
At the moment the docker containers allow running on linux only. 
This reduced the complexity because its only 1 build target.

Desktops and even Mobile is possible.

I tried using DevBox ( which is a wrapper for nix ) to bring in the dependencies for Mac and it worked and compiled. But thats only Mac.

For golang, there are 2 main ways.

Embedding, for example like this https://github.com/cogentcore/webgpu/tree/main/wgpu/lib 

Non embedding, which is what is done now in this repo.

Many of them are quite huge. About 300 MB per binary for OS/ISA.  Github is git LFS so its ok. 

I have built top a list of where to download them from and a downloader and so could add this to get the ball rolling.

**Comment by johbar** [comment]
I'm not a fan of this kind of "embedding" you mention. [go-fitz](https://github.com/gen2brain/go-fitz/tree/master/libs) does this, but optionally. Putting object file archives (static libs) in Git repos means there are opaque blobs of executable code people pull into there builds. 👎️

This might be ignorant of me and unsatisfying for you. But I don't care that much for supporting others OSes than Linux which I use for development mostly. I think most servers run on Linux, too. Their package managers and (multi-stage) container builds solve most of the problems we once had with managing dependency hell. 

Nevertheless, if you want to share your downloader script I can add it to the repo after reviewing it. Might be of use for MacOS users.

**Comment by johbar** [comment]
I migrated the code to purego and also build a solution for Mac and Linux not requiring Docker or manual library setup by embedding the PDFium shared lib into the service binary. It's tested on a GH workflow. 

Downloads available here: https://github.com/johbar/text-extraction-service/releases/latest
